# Generated by Django 2.1.2 on 2018-10-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='title',
        ),
    ]
